local M = {}

---Fetch schema info and generate ER diagram
function M.generate()
  local conn_mgr = require("sql-lens.connections")
  local bufnr = vim.api.nvim_get_current_buf()
  local conn = conn_mgr.get_active(bufnr)
  if not conn then
    vim.notify("SqlLens: No active connection", vim.log.levels.WARN)
    return
  end

  vim.notify("SqlLens: Building ER diagram...", vim.log.levels.INFO)

  conn:list_tables(function(err, tables)
    if err or #tables == 0 then
      vim.notify("SqlLens: No tables found", vim.log.levels.WARN)
      return
    end

    -- Fetch columns for all tables
    local table_cols = {}
    local done_cols = 0
    local total = #tables

    for _, tbl in ipairs(tables) do
      conn:list_columns(tbl, function(_, cols)
        table_cols[tbl] = cols or {}
        done_cols = done_cols + 1
        if done_cols == total then
          -- Now fetch foreign keys
          if conn.list_foreign_keys then
            conn:list_foreign_keys(function(_, fks)
              M._build(tables, table_cols, fks or {}, conn)
            end)
          else
            M._build(tables, table_cols, {}, conn)
          end
        end
      end)
    end
  end)
end

---Build Mermaid ER diagram and open in browser
function M._build(tables, table_cols, fks, conn)
  local mermaid = { "erDiagram" }

  -- Add tables with columns
  for _, tbl in ipairs(tables) do
    table.insert(mermaid, "  " .. tbl .. " {")
    for _, col_info in ipairs(table_cols[tbl] or {}) do
      local col_name = col_info:match("^(%S+)") or col_info
      local col_type = col_info:match("%s+(.+)$") or ""
      -- Clean type for mermaid (no spaces, no parens)
      col_type = col_type:gsub("%s+", "_"):gsub("[%(%),%[%]]", "")
      if col_type == "" then col_type = "unknown" end
      -- Check if it's a PK or FK
      local attr = ""
      if col_name == "id" or col_name:match("_id$") == nil and col_name == "id" then
        attr = " PK"
      end
      for _, fk in ipairs(fks) do
        if fk.from_table == tbl and fk.from_column == col_name then
          attr = " FK"
          break
        end
      end
      table.insert(mermaid, string.format("    %s %s%s", col_type, col_name, attr))
    end
    table.insert(mermaid, "  }")
  end

  -- Add relationships from foreign keys
  local seen_rels = {}
  for _, fk in ipairs(fks) do
    local key = fk.from_table .. "->" .. fk.to_table
    if not seen_rels[key] then
      seen_rels[key] = true
      table.insert(mermaid, string.format(
        '  %s }o--|| %s : "%s → %s"',
        fk.from_table, fk.to_table, fk.from_column, fk.to_column
      ))
    end
  end

  local mermaid_code = table.concat(mermaid, "\n")
  local db_name = (conn.config.dbname or conn.config.name or "database")

  -- Generate HTML
  local html = string.format([[<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>ER Diagram — %s</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      background: #0d1117;
      color: #c9d1d9;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
      display: flex;
      flex-direction: column;
      min-height: 100vh;
    }
    header {
      background: #161b22;
      border-bottom: 1px solid #30363d;
      padding: 16px 24px;
      display: flex;
      align-items: center;
      gap: 12px;
    }
    header h1 {
      font-size: 20px;
      font-weight: 600;
    }
    header .badge {
      background: #238636;
      color: white;
      padding: 2px 8px;
      border-radius: 12px;
      font-size: 12px;
    }
    header .info {
      color: #8b949e;
      font-size: 14px;
      margin-left: auto;
    }
    .toolbar {
      background: #161b22;
      border-bottom: 1px solid #30363d;
      padding: 8px 24px;
      display: flex;
      gap: 8px;
    }
    .toolbar button {
      background: #21262d;
      color: #c9d1d9;
      border: 1px solid #30363d;
      padding: 5px 16px;
      border-radius: 6px;
      cursor: pointer;
      font-size: 13px;
    }
    .toolbar button:hover { background: #30363d; }
    #diagram-container {
      flex: 1;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 24px;
      overflow: auto;
    }
    .mermaid {
      background: #161b22;
      border-radius: 8px;
      padding: 24px;
      border: 1px solid #30363d;
    }
    .mermaid svg { max-width: 100%%; }
  </style>
</head>
<body>
  <header>
    <h1>🗃️ ER Diagram</h1>
    <span class="badge">%s</span>
    <span class="info">%d tables · %d relationships · Generated by sql-lens.nvim</span>
  </header>
  <div class="toolbar">
    <button onclick="zoomIn()">🔍 Zoom In</button>
    <button onclick="zoomOut()">🔍 Zoom Out</button>
    <button onclick="resetZoom()">↺ Reset</button>
    <button onclick="downloadSVG()">💾 Save SVG</button>
  </div>
  <div id="diagram-container">
    <pre class="mermaid">
%s
    </pre>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <script>
    mermaid.initialize({
      startOnLoad: true,
      theme: 'dark',
      er: { useMaxWidth: false, layoutDirection: 'TB' },
      themeVariables: {
        primaryColor: '#238636',
        primaryTextColor: '#c9d1d9',
        primaryBorderColor: '#30363d',
        lineColor: '#58a6ff',
        secondaryColor: '#21262d',
        tertiaryColor: '#161b22',
      }
    });

    let scale = 1;
    function zoomIn() { scale *= 1.2; applyZoom(); }
    function zoomOut() { scale /= 1.2; applyZoom(); }
    function resetZoom() { scale = 1; applyZoom(); }
    function applyZoom() {
      document.querySelector('.mermaid svg').style.transform = 'scale(' + scale + ')';
      document.querySelector('.mermaid svg').style.transformOrigin = 'top left';
    }
    function downloadSVG() {
      const svg = document.querySelector('.mermaid svg');
      const data = new XMLSerializer().serializeToString(svg);
      const blob = new Blob([data], { type: 'image/svg+xml' });
      const a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = '%s_er_diagram.svg';
      a.click();
    }
  </script>
</body>
</html>]],
    db_name, db_name, #tables, #fks,
    mermaid_code, db_name:gsub("[^%w]", "_")
  )

  -- Save to temp file and open in browser
  local tmpfile = vim.fn.tempname() .. ".html"
  local f = io.open(tmpfile, "w")
  if not f then
    vim.notify("SqlLens: Cannot create temp file", vim.log.levels.ERROR)
    return
  end
  f:write(html)
  f:close()

  -- Open in browser (cross-platform)
  local open_cmd
  if vim.fn.has("win32") == 1 then
    open_cmd = { "cmd", "/c", "start", "", tmpfile }
  elseif vim.fn.has("mac") == 1 then
    open_cmd = { "open", tmpfile }
  else
    open_cmd = { "xdg-open", tmpfile }
  end
  vim.fn.jobstart(open_cmd, { detach = true })

  vim.notify(string.format("SqlLens: ER diagram opened (%d tables, %d relationships)", #tables, #fks), vim.log.levels.INFO)
end

return M
